//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Skyline.DataMiner.SDM.Registration
{
	using System;

	using Skyline.DataMiner.Net.Apps.DataMinerObjectModel;
	using Skyline.DataMiner.Net.Sections;
	using Skyline.DataMiner.SDM;

	[SdmDomMapper]
	internal static class SolutionRegistrationDomMapper
	{
		internal const string ModuleId = "(slc)standard_data_model";
		internal static DomDefinitionId DomDefinitionId = new DomDefinitionId(new Guid("ed4e8378-7e45-4ab4-873e-7c3ddd379b89"))
		{ ModuleId = ModuleId };
		internal static class SolutionRegistrationProperties
		{
			internal static SectionDefinitionID SectionDefinitionId = new SectionDefinitionID(new Guid("f16970b4-c311-4900-8dfd-50a6879b8f7b"))
			{ ModuleId = ModuleId };
			internal static FieldDescriptorID ID = new FieldDescriptorID(new Guid("6b2c6359-e653-4c4d-a88c-6802cda1d7d2"));
			internal static FieldDescriptorID DisplayName = new FieldDescriptorID(new Guid("5bfb0b36-0181-4529-9a98-4a3485f011c7"));
			internal static FieldDescriptorID Version = new FieldDescriptorID(new Guid("8b532bb2-974a-40da-929c-e7a84592046a"));
			internal static FieldDescriptorID DefaultApiScriptName = new FieldDescriptorID(new Guid("ffb69193-eb5b-4923-850c-df375c482ad1"));
			internal static FieldDescriptorID DefaultApiEndpoint = new FieldDescriptorID(new Guid("9d49ac29-aa64-4468-96ab-c88dda0dd4e0"));
			internal static FieldDescriptorID VisualizationEndpoint = new FieldDescriptorID(new Guid("012b0a5b-252f-4ea7-8008-546da1e1c7b2"));
			internal static FieldDescriptorID UninstallScript = new FieldDescriptorID(new Guid("03f9f28c-d8b2-4cfa-9e79-607fe0c262b3"));
			internal static FieldDescriptorID Models = new FieldDescriptorID(new Guid("01d76fa0-8ebb-4eb1-885b-6f0e209c5ebb"));
		}
	}
}